### ISSUE TITLE
Loading currfile-abspath before currfile raises error?

### ISSUE THREAD

**Issue by user202729** [MartinScharrer/currfile#1]
Example:

```
\documentclass{article}
\usepackage{currfile-abspath}
\usepackage{currfile}
\begin{document}


\end{document}
```

I think since currfile-abspath is documented as "can be used standalone" the above should be supported?  
(not necessarily literally like that but maybe some package loads currfile-abspath only then another package loads currfile.)

**Comment by MartinScharrer** [comment]
Error message is:
```
LaTeX2e <2022-11-01>
L3 programming layer <2022-11-02>
(d:/texlive/2022/texmf-dist/tex/latex/base/article.cls
Document Class: article 2022/07/02 v1.4n Standard LaTeX document class
(d:/texlive/2022/texmf-dist/tex/latex/base/size10.clo))
(d:/texlive/2022/texmf-dist/tex/latex/currfile/currfile-abspath.sty)
(d:/texlive/2022/texmf-dist/tex/latex/currfile/currfile.sty
(d:/texlive/2022/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(d:/texlive/2022/texmf-dist/tex/latex/graphics/keyval.sty)
(d:/texlive/2022/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty)
(d:/texlive/2022/texmf-dist/tex/latex/kvsetkeys/kvsetkeys.sty))

! LaTeX Error: Command \currfile@mainext already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.21 }
      %
?
```

**Comment by MartinScharrer** [comment]
Thank you for reporting this issue.
Loading `currfile-absfile` alone is ok. Loading it before `currfile` is problematic if that package is loaded with contradicting options. It is recommended to load `currfile` very early before any other packages. 

Nevertheless, I added a fix to the package now.

**Comment by user202729** [comment]
More than one year later, I encounter the error again, and notice that the new version hasn't been uploaded to CTAN. Can you upload it?

**Comment by MartinScharrer** [comment]
Sorry, I will release it shortly.

**Comment by MartinScharrer** [comment]
I just uploaded it as [v1.0](https://github.com/MartinScharrer/currfile/releases/tag/v1.0) . Should be available on CTAN within 1-2 days, +1-2 days in the distributions.
